langueage: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t naitao/docker-react -f Dockerfile.dev .

script:
  - docker run naitao/docker-react npm run test -- --coverage